name: Shellcheck

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  linux:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: [22.3.4, "23.0"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: gleam-lang/setup-erlang@v1.0.0
      with:
        otp-version: ${{ matrix.otp_version }}

    - name: Compile
      run: rebar3 compile

    - name: Dialyzer
      run: rebar3 dialyzer
